### ISSUE TITLE
an example of how to run chimp on circleCI would be nice

### ISSUE THREAD

**Issue by Alino** [xolvio/chimp#193]
I am trying to run chimp on circleCI
here is part of my circle.yml
```
    # Test the app with Chrome
    - cd app && nohup meteor --settings .deploy/build/settings.json &
    - sleep 30 && curl --retry 10 --retry-delay 5 -v http://localhost:3000
    - cd app/tests/cucumber && chimp --ddp=http://localhost:3000 --browser=chrome --jsonOutput=cucumber_output.json

    # create artifacts
    - mkdir -p $CIRCLE_ARTIFACTS/chrome
    - cp app/.meteor/local/log/*.log $CIRCLE_ARTIFACTS/chrome
```

could you please advise me, how could I improve this?
**running the meteor in background** with nohup has some problems:

```
sleep 30 && curl --retry 10 --retry-delay 5 -v http://localhost:3000
** About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1... Connection refused
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host
 About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1... Connection refused
* couldn't connect to host
* Closing connection #0

sleep 30 && curl --retry 10 --retry-delay 5 -v http://localhost:3000 returned exit code 7
curl: (7) couldn't connect to host sleep 30 && curl --retry 10 --retry-delay 5 -v http://localhost:3000 returned exit code 7
```

**Comment by clayne11** [comment]
+1 - I would like to run this in CI but it's not as simple now that Meteor needs to run in a separate process

**Comment by Alino** [comment]
@clayne11 I found out that you have to run it with ```background: true``` property in your circle.yml
more info here https://circleci.com/docs/background-process

this is how I currently run chimp on circle:
```
    # CHIMP CUCUMBER - Test the app with Chrome
    - cd app && meteor --settings .deploy/build/settings.json:
        background: true
        environment:
          MONGO_URL: "mongodb://127.0.0.1:27018/kuknito"
          MONGO_OPLOG_URL: "mongodb://127.0.0.1:27018/local"
    - sleep 10
    - cd app/tests/cucumber && chimp --ddp=http://localhost:3000 --browser=chrome --jsonOutput=$CIRCLE_TEST_REPORTS/chrome.cucumber --screenshotsPath=$CIRCLE_ARTIFACTS/chrome --saveScreenshots
```
